/slam_toolbox:
  ros__parameters:
    angle_variance_penalty: 1.0
    base_frame: base_link
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_loss_function: HuberLoss #None
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LM
    coarse_angle_resolution: 0.0349
    coarse_search_angle_offset: 0.349
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    debug_logging: false
    distance_variance_penalty: 0.5
    do_loop_closing: true
    enable_interactive_mode: false
    fine_search_angle_offset: 0.00349
    interactive_mode: false
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.6
    loop_search_maximum_distance: 3.0
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    map_file_name: maps/ORIGIN_MAP
    map_frame: map
    map_name: /map
    map_start_at_dock: true
    map_start_pose:
    - -1.28700493
    - -0.61549585
    - -0.7802
    map_update_interval: 10.0
    max_laser_range: 10.0
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.05
    minimum_time_interval: 0.5
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.3
    mode: localization
    odom_frame: odom
    paused_new_measurements: false
    paused_processing: false
    position_covariance_scale: 1.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    resolution: 0.05
    scan_buffer_maximum_scan_distance: 10.0
    scan_buffer_size: 10
    scan_queue_size: 20
    scan_topic: scan
    solver_plugin: solver_plugins::CeresSolver
    tf_buffer_duration: 30.0
    throttle_scans: 1  # 0
    transform_publish_period: 0.02
    transform_timeout: 0.5
    use_map_saver: true
    use_response_expansion: true
    use_scan_barycenter: true
    use_scan_matching: true
    use_sim_time: true
    yaw_covariance_scale: 1.0

